<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Products\" />
    <Folder Include="Persistence\Orders\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payage.Application\Payage.Application.csproj" />
    <ProjectReference Include="..\Payage.Domain\Payage.Domain.csproj" />
  </ItemGroup>

</Project>
